### ISSUE TITLE
👷 인프라 : ELK docker-compose 서버 작업 

### ISSUE THREAD

**Issue by hanseu9839** [ITZipProject/itzip_back#52]
현재 docker-compose 를 사용하여 세팅은 완료 -> hosting 에러 발생

**Comment by CodeJesterND** [comment]
엘라스틱 깃허브 참고하여 호스팅 에러 발생 해결하였습니다 :)

- Docker build, setup, profile 옵션에 대해 다시 돌아보는 계기가 되었습니다 👍
